export let students = [{
    name:"Harry Potter",
    alternate_names:[],
    species:"human",
    gender:"male",
    house:"Gryffindor",
    dateOfBirth:"31-07-1980",
    yearOfBirth:1980,
    wizard:true,
    ancestry:"half-blood",
    eyeColour:"green",
    hairColour:"black",
    wand:{"wood":"holly",
    core:"phoenix feather",
    length:11},
    patronus:"stag",
    hogwartsStudent:true,
    hogwartsStaff:false,
    actor:"Daniel Radcliffe",
    alternate_actors:[],
    alive:true,
    image:"http://hp-api.herokuapp.com/images/harry.jpg",
    logo: "../images/leon.png"
},

{
 name:"Hermione Granger",
 alernate_names:[],
 spcies:"human",
 geder:"female",
 house:"Gryffindor",
 daeOfBirth:"19-09-1979",
 yerOfBirth:1979,
 wiard:true,
 anestry:"muggleborn",
 eyColour:"brown",
 harColour:"brown",
 wad:{"wood":"vine",
 coe:"dragon heartstring",
 legth:""},
 paronus:"otter",
 howartsStudent:true,
 howartsStaff:false,
 acor:"Emma Watson",
 alernate_actors:[],
 alve:true,
 image:"https://tupersonajefavorito.com/wp-content/uploads/2018/04/hermaioni-granger-3.jpg",
 logo: "../images/leon.png"
},

{
    name:"Ron Weasley",
    alternate_names:["Dragomir Despard"],
    species:"human",
    gender:"male",
    house:"Gryffindor",
    dateOfBirth:"01-03-1980",
    yearOfBirth:1980,
    wizard:true,
    ancestry:"pure-blood",
    eyeColour:"blue",
    hairColour:"red",
    wand:{"wood":"willow",
    core:"unicorn tail-hair",
    length:14},
    patronus:"Jack Russell terrier",
    hogwartsStudent:true,
    hogwartsStaff:false,
    actor:"Rupert Grint",
    alternate_actors:[],
    alive:true,
    image:"http://hp-api.herokuapp.com/images/ron.jpg",
    logo: "../images/leon.png"

},

{
    name:"Draco Malfoy",
    alternate_names:[],
    species:"human",
    gender:"male",
    house:"Slytherin",
    dateOfBirth:"05-06-1980",
    yearOfBirth:1980,
    wizard:true,
    ancestry:"pure-blood",
    eyeColour:"grey",
    hairColour:"blonde",
    wand:{"wood":"hawthorn",
    core:"unicorn tail-hair",
    length:10},
    patronus:"",
    hogwartsStudent:true,
    hogwartsStaff:false,
    actor:"Tom Felton",
    alternate_actors:[],
    alive:true,
    image:"http://hp-api.herokuapp.com/images/draco.jpg",
    logo: "../images/serpiente.png"
    

},

{
    name:"Cedric Diggory",
    alternate_names:[],
    species:"human",
    gender:"male",
    house:"Hufflepuff",
    dateOfBirth:"",
    yearOfBirth:1977,
    wizard:true,
    ancestry:"",
    eyeColour:"grey",
    hairColour:"brown",
    wand:{"wood":"ash",
    core:"unicorn hair",
    length:12.25},
    patronus:"",
    hogwartsStudent:true,
    hogwartsStaff:false,
    actor:"Robert Pattinson",
    alternate_actors:[],
    alive:false,
    image:"http://hp-api.herokuapp.com/images/cedric.png",
    logo:"../images/nutria.png"
},

{
    name:"Cho Chang",
    alternate_names:[],
    species:"human",
    gender:"female",
    house:"Ravenclaw",
    dateOfBirth:"",
    yearOfBirth:"",
    wizard:true,
    ancestry:"",
    eyeColour:"brown",
    hairColour:"black",
    wand:{"wood":"",
    core:"",
    length:""},
    patronus:"swan",
    hogwartsStudent:true,
    hogwartsStaff:false,
    actor:"Katie Leung",
    alternate_actors:[],
    alive:true,
    image:"http://hp-api.herokuapp.com/images/cho.jpg",
    logo: "../images/aguila.png"

},

{
    name:"Neville Longbottom",
    alternate_names:[],
    species:"human",
    gender:"male",
    house:"Gryffindor",
    dateOfBirth:"30-07-1980",
    yearOfBirth:1980,
    wizard:true,
    ancestry:"pure-blood",
    eyeColour:"",
    hairColour:"blonde",
    wand:{"wood":"cherry",
    core:"unicorn tail-hair",
    length:13},
    patronus:"",
    hogwartsStudent:true,
    hogwartsStaff:false,
    actor:"Matthew Lewis",
    alternate_actors:[],
    alive:true,
    image:"http://hp-api.herokuapp.com/images/neville.jpg",
    logo:"../images/leon.png"
},

{
    name:"Luna Lovegood",
    alternate_names:[],
    species:"human",
    gender:"female",
    house:"Ravenclaw",
    dateOfBirth:"13-02-1981",
    yearOfBirth:1981,"wizard":true,
    ancestry:"",
    eyeColour:"grey",
    hairColour:"blonde",
    wand:{"wood":"",
    core:"",
    length:""},
    patronus:"hare",
    hogwartsStudent:true,
    hogwartsStaff:false,
    actor:"Evanna Lynch",
    alternate_actors:[],
    alive:true,
    image:"http://hp-api.herokuapp.com/images/luna.jpg",
    logo: "../images/aguila.png"
},  

{
    name:"Ginny Weasley",
    alternate_names:[],
    species:"human",
    gender:"female",
    house:"Gryffindor",
    dateOfBirth:"11-08-1981",
    yearOfBirth:1981,
    wizard:true,
    ancestry:"pure-blood",
    eyeColour:"brown",
    hairColour:"red",
    wand:{"wood":"yew",
    core:"",
    length:""},
    patronus:"horse",
    hogwartsStudent:true,
    hogwartsStaff:false,
    actor:"Bonnie Wright",
    alternate_actors:[],
    alive:true,
    image:"http://hp-api.herokuapp.com/images/ginny.jpg",
    logo:"../images/leon.png"
},

{
    name:"Vincent Crabbe",
    alternate_names:[],
    species:"human",
    gender:"male",
    house:"Slytherin",
    dateOfBirth:"",
    yearOfBirth:"",
    wizard:true,
    ancestry:"pure-blood",
    eyeColour:"black",
    hairColour:"black",
    wand:{"wood":"",
    core:"",
    length:""},
    patronus:"",
    hogwartsStudent:true,
    hogwartsStaff:false,
    actor:"Jamie Waylett",
    alternate_actors:[],
    alive:false,
    image:"http://hp-api.herokuapp.com/images/crabbe.jpg",
    logo: "../images/serpiente.png"
},

{
    name:"Gregory Goyle",
    alternate_names:[],
    species:"human",
    gender:"male",
    house:"Slytherin",
    dateOfBirth:"",
    yearOfBirth:"",
    wizard:true,
    ancestry:"pure-blood",
    eyeColour:"",
    hairColour:"brown",
    wand:{"wood":"",
    core:"",
    length:""},
    patronus:"",
    hogwartsStudent:true,
    hogwartsStaff:false,
    actor:"Josh Herdman",
    alternate_actors:[],
    alive:true,
    image:"http://hp-api.herokuapp.com/images/goyle.jpg",
    logo: "../images/serpiente.png"
},

{
    name:"Percy Weasley",
    alternate_names:["Perce"],
    species:"human",
    gender:"male",
    house:"Gryffindor",
    dateOfBirth:"",
    yearOfBirth:"",
    wizard:true,
    ancestry:"pure-blood",
    eyeColour:"",
    hairColour:"red",
    wand:{"wood":"",
    core:"",
    length:""},
    patronus:"",
    hogwartsStudent:true,
    hogwartsStaff:false,
    actor:"Chris Rankin",
    alternate_actors:[],
    alive:true,
    image:"https://img.wattpad.com/cover/217838082-256-k975822.jpg",
    logo:"../images/leon.png"
},

{
    name:"Fred Weasley",
    alternate_names:[],
    species:"human",
    gender:"male",
    house:"Gryffindor",
    dateOfBirth:"",
    yearOfBirth:"",
    wizard:true,
    ancestry:"pure-blood",
    eyeColour:"",
    hairColour:"red",
    wand:{"wood":"",
    core:"",
    length:""},
    patronus:"",
    hogwartsStudent:true,
    hogwartsStaff:false,
    actor:"James Phelps",
    alternate_actors:[],
    alive:false,
    image:"http://pm1.narvii.com/6970/237cf3e55edaf5ddc7c095c9a818571d4a4b0b47r1-1080-1472v2_uhq.jpg",
    logo:"../images/leon.png"
},
]
 